# Generated by Django 5.0.1 on 2024-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Kısa Açıklama'),
        ),
    ]
