# Generated by Django 5.0.1 on 2024-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_socialmedia_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon_paket_link',
            field=models.TextField(blank=True, null=True, verbose_name='kullanilacak olan icon paketinin linki'),
        ),
    ]
