# Generated by Django 5.0.1 on 2024-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_socialmedia_icon_paket_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200, verbose_name='Yetenek Adı')),
                ('skill_value', models.IntegerField(verbose_name='Yetenek Değeri (0-100)')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hakkımda Başlığı')),
                ('content', models.TextField(verbose_name='Hakkımda İçeriği')),
                ('skills', models.ManyToManyField(to='main.skills', verbose_name='Yetenekler')),
            ],
            options={
                'verbose_name': 'Hakkımda',
                'verbose_name_plural': 'Hakkımda',
            },
        ),
    ]
