# Generated by Django 5.0.1 on 2024-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='Okul Adı')),
                ('department', models.CharField(max_length=200, verbose_name='Bölüm')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('job', models.CharField(max_length=200, verbose_name='Meslek')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.ManyToManyField(to='main.education', verbose_name='Eğitimler'),
        ),
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.ManyToManyField(to='main.experience', verbose_name='Deneyimler'),
        ),
    ]
