# Generated by Django 5.0.1 on 2024-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_education_experience_about_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.PositiveIntegerField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.PositiveIntegerField(verbose_name='Başlangıç Tarihi'),
        ),
    ]
