# Generated by Django 5.0.1 on 2024-02-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveIntegerField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.PositiveIntegerField(verbose_name='Başlangıç Tarihi'),
        ),
    ]
