# Generated by Django 5.0.1 on 2024-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='image',
            field=models.ImageField(default='test', upload_to='works/', verbose_name='Proje Görseli'),
            preserve_default=False,
        ),
    ]
