# Generated by Django 5.0.1 on 2024-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_works_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('mail', models.CharField(max_length=50, verbose_name='E-posta')),
                ('subject', models.CharField(max_length=100, verbose_name='Konu')),
                ('message', models.CharField(max_length=1000, verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'Gelen Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
            },
        ),
    ]
