# Generated by Django 5.0.1 on 2024-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_settings',
            name='mail',
            field=models.CharField(default='hamzabilen2121@gmail.com', max_length=100, verbose_name='mail ( contact sayfasında doldurulan form bu maile gelecek )'),
            preserve_default=False,
        ),
    ]
